Add partial 2D dam break in ex1.c
RDycore/toy-problems pull request #3
Opened 2022-10-24 17:42 UTC by donghuix

Follow partial 2D dam break on a flat surface from Section 6.1 of https://www.sciencedirect.com/science/article/pii/S0045782509002527#fd1

2022-10-24 19:20 UTC, bishtgautam requested changes
Few minor comments

2022-10-24 19:20 UTC, bishtgautam commented on swe_roe/show_ex1.m
> +y = 1 : 200;
How about letting `ex1.c` save this information and then having the matlab code read it?

2022-10-24 19:20 UTC, bishtgautam commented on swe_roe/ex1.c
> +        PetscCall(PetscOptionsReal("-hd","hd","",user->hd,&user->hd,NULL));
How about adding a check to ensure the heights provided by a user are non-negative?

2022-10-24 19:20 UTC, bishtgautam commented on swe_roe/ex1.c
> +            else if (i >= 105 && j >= 95 && j < 105) {
I believe the location of the wall is assuming `user->hx = user->hy = 1.0`. The code should be modified to explicitly take into account `hx` and `hy`, so the wall remains in the same location when the grid spacing is modified.

2022-10-24 19:22 UTC, bishtgautam commented on swe_roe/ex1.c
> +            else if (i >= 105 && j >= 95 && j < 105) {
@donghuix Let me know if you think addressing this comment requires significant work that you would prefer to fix in a future PR.

2022-10-24 22:30 UTC, donghuix commented
@bishtgautam, I updated the code based on your comments in above commit. Please let me know if you have other comments.

2022-10-25 16:08 UTC, bishtgautam approved these changes

2022-10-25 16:09 UTC, merged